website/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),
    # /music/id(71)
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /music/album/add
    path('album/add', views.AlbumCreate.as_view(), name='album-add')

]

website/projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include

#Table of contents for your website.
#Something.com/urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('projects/', include('projects.urls')),
]

website/music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk })

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/projects/models.py
from django.db import models

# Create your models here.

website/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album,Song


'''
Benytter generic views. Generic views er oprettet fordi udviklere altid bruger de samme generic functions (se en liste af items, og details på specifikke items)
Derfor er der blevet lavet generic views i Django som gør det nemmere at arbejde med de functions.
'''


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

    '''
        Når man skal bruge listen ude i view skal man kalde objects_list
        Hvis man vil ændre navnet på denne variabel kan man override følgende
        context_object_name = 'album_list'
    '''


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


''' Måden at gøre det på som ikke er Django generic.

from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums' : all_albums})

def detail(request, album_id):
    #Try to get object, if not found it will raise a 404
    album = get_object_or_404(Album, id=album_id)
    return render(request, 'music/detail.html', {'album' : album})
'''

website/projects/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("This is the projects homepage")

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                       <div class="col-sm-offset-2 col-sm-10">
                           <button type="submit" class="btn btn-success">Submit</button>
                       </div>
                    </div>

                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    ﻿
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index'%}">Viberr</a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index'%}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'music:index'%}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add'%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'music:index'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>


        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <center><img src="{{ album.album_logo }}" width="200" height="200"></center>

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        <br>
    {% endfor %}

{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-10">
            <span class="text-danger small">{{ field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
        <ul>
            {% for album in object_list %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>
{% endblock %}